<script>
$("#breadcrumb-title").html('<?=env('APP_NAME')?>');
$("#breadcrumb-title").append(' / FileControl / Generar Tablas');
</script>

<div class="m-portlet m-portlet--mobile">
	<div class="m-portlet__head">
		<div class="m-portlet__head-caption">
			<div class="m-portlet__head-title">
				<h3 class="m-portlet__head-text">
					Generar Tablas:
				</h3>
			</div>
		</div>
	</div>
	<div class="m-portlet__body">
		<style>
		    img.menu {
		        display: block;
		        max-width: 100%;
		        height: auto;
						margin: auto;
						z-index:2;
		    }
		</style>
		<!-- Image Map Generated by http://www.image-map.net/ -->
			<img src="img/menu.svg" usemap="#image-map" class="menu">
			<map name="image-map">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/reprocesar/fgj');" alt="FGJ" title="FGJ" href="" coords="332,450,107" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/reprocesar/cbp');" alt="CBP" title="CBP" href="" coords="560,186,103" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/reprocesar/cnb');" alt="CNB" title="CNB" href="" coords="142,196,102" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_cbp_fgj');" alt="CBP-FGJ" title="CBP-FGJ" href="" coords="550,394,62" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_cbp_cnb');" alt="CNB-CBP" title="CNB-CBP" href="" coords="351,103,59" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_cnb_fgj');" alt="CNB-FGJ" title="CNB-FGJ" href="" coords="122,393,62" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_unificada');" alt="CBP-CNB-FGJ" title="CBP-CNB-FGJ" href="" coords="371,250,68" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_duplicados_cbp_fgj');" alt="CBP-FGJ-DUP" title="CBP-FGJ-DUP" href="" coords="623,473,26" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_duplicados_cnb_fgj');" alt="CNB-FGJ-DUP" title="CNB-FGJ-DUP" href="" coords="53,326,27" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_duplicados_cbp_cnb');" alt="CNB-CBP-DUP" title="CNB-CBP-DUP" href="" coords="267,54,30" shape="circle">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_duplicados_unificada');" alt="CBP-CNB-FGJ-DUP" title="CBP-CNB-FGJ-DUP" href="" coords="272,303,34" shape="circle">
			</map>

	</div>

</div>

<script>
    $(function () {
        ImageMap('img[usemap]');
    });
    function selectRegion(region) {
        document.querySelector("img").setAttribute('src', 'image-map-' + region + '.png');
    }

</script>
