<script>
$("#breadcrumb-title").html('<?=env('APP_NAME')?>');
$("#breadcrumb-title").append(' / FileControl / Generar Tablas');
</script>

<div class="m-portlet m-portlet--mobile">
	<div class="m-portlet__head">
		<div class="m-portlet__head-caption">
			<div class="m-portlet__head-title">
				<h3 class="m-portlet__head-text">
					Generar Tablas:
				</h3>
			</div>
		</div>
	</div>
	<div class="m-portlet__body">
		<style>
		body { background-color:#333; color:#fff;}
		h1 { margin:150px auto 30px auto; font-family:'Roboto';margin-left:5em;}
		    img.menu {
		        display: block;
		        max-width: 50%;
		        height: auto;
						margin: auto;
		    }
		</style>
			<!-- Image Map Generated by http://www.image-map.net/ -->
			<map name="image-map">
				<img src="img/ven-gears.png" usemap="#image-map" class="menu">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','desaparecidos/upload');" alt="CBP" title="CBP" coords="386,574,369,518,276,517,279,402,364,405,390,327,315,280,368,180,446,225,503,169,459,94,558,37,605,111,681,89,681,2,796,3,797,87,870,110,919,33,1016,89,976,169,1031,225,1107,179,1163,280,1088,327,1105,398,1195,405,1195,514,1110,514,1093,574,1078,571,1074,483,963,483,960,572,885,597,838,518,741,577,644,520,599,595,519,572,519,483,406,486,402,572" shape="poly">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','desaparecidos/upload');" alt="CNB" title="CNB" coords="740,1192,780,1234,740,1309,839,1369,881,1298,959,1313,959,1397,1079,1401,1073,1313,1152,1291,1201,1365,1297,1313,1253,1236,1309,1179,1383,1221,1445,1124,1368,1082,1387,1007,1477,1000,1477,885,1388,887,1368,814,1445,765,1387,666,1309,712,1253,657,1298,576,1198,516,1156,594,1096,578,1090,593,1163,640,1104,735,1031,694,976,750,1018,828,919,879,922,996,835,1001,818,1075,882,1125,830,1219,746,1178" shape="poly">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','desaparecidos/upload');" alt="FGJ" title="FGJ" coords="742,1192,701,1233,742,1310,643,1368,599,1289,520,1310,520,1399,408,1399,403,1310,331,1288,284,1366,189,1309,227,1233,171,1175,92,1218,35,1119,116,1072,96,998,4,997,6,884,92,882,113,808,39,761,92,665,171,704,228,649,185,569,283,516,327,591,387,573,390,593,314,636,369,735,448,688,502,746,459,825,557,881,561,1004,651,1004,668,1077,592,1129,646,1223,729,1176" shape="poly">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_cnb_fgj');" alt="CNB-FGJ" title="CNB-FGJ" coords="595,1127,668,1073,647,1005,558,1000,561,885,650,881,665,828,678,828,684,915,792,917,793,829,814,829,828,880,916,892,917,996,834,996,817,1075,885,1122,827,1215,738,1171,647,1215" shape="poly">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_cbp_cnb');" alt="CBP-CNB" title="CBP-CNB" coords="738,691,785,649,745,576,839,519,886,598,959,574,963,482,1074,482,1078,581,1161,641,1104,730,1032,688,979,748,1016,827,917,880,875,808,814,828,812,808,885,761,828,665,751,712" shape="poly">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_cbp_fgj');" alt="CBP-FGJ" title="CBP-FGJ" coords="668,810,663,825,605,808,557,878,464,825,501,746,449,693,365,729,315,637,399,579,406,487,514,485,515,575,597,591,642,522,740,574,694,648,738,693,724,704,647,664,594,762" shape="poly">
			    <area href="javaScript:void(0);" onclick="carga_archivo('contenedor_principal','filecontrol/generar_unificada');" alt="CBP-CNB-FGJ" title="CBP-CNB-FGJ" coords="684,908,791,913,791,808,879,762,827,668,734,714,646,663,595,763,676,814" shape="poly">
			</map>
	</div>

</div>

<script>
    $(function () {
        ImageMap('img[usemap]');
    });
    function selectRegion(region) {
        document.querySelector("img").setAttribute('src', 'image-map-' + region + '.png');
    }

</script>
