<script>
$("#breadcrumb-title").html('<?=env('APP_NAME')?>');
$("#breadcrumb-title").append(' / FileControl / Menu');
</script>

<div class="m-portlet m-portlet--mobile">
	<div class="m-portlet__head">
		<div class="m-portlet__head-caption">
			<div class="m-portlet__head-title">
				<h3 class="m-portlet__head-text">
					Seleccione para visualizar
				</h3>
			</div>
		</div>
	</div>
	<div class="m-portlet__body">
		<style>
		body { background-color:#333; color:#fff;}
		h1 { margin:150px auto 30px auto; font-family:'Roboto';margin-left:5em;}
		    img.menu {
		        display: block;
		        max-width: 50%;
		        height: auto;
						margin: auto;
		    }
		</style>
			<!-- Image Map Generated by http://www.image-map.net/ -->
		<map name="image-map">
			<img src="img/ven.png" usemap="#image-map" class="menu">
			    <area href="javascript:void(0);" onclick="carga_archivo('contenedor_principal','cbp');" alt="CBP" title="CBP" coords="285,530,343,511,422,494,511,483,581,494,643,509,733,543,782,572,850,536,922,505,1005,487,1094,487,1193,502,1279,533,1260,372,1208,244,1070,94,853,6,714,0,555,51,426,150,343,262,307,360,288,464" shape="poly">
			    <area href="javascript:void(0);" onclick="carga_archivo('contenedor_principal','fgj');" alt="FGJ" title="FGJ" coords="761,1416,656,1316,599,1225,567,1124,551,1035,551,963,479,925,411,869,351,796,304,699,279,619,268,558,146,644,67,746,22,857,0,992,24,1159,78,1275,182,1390,328,1469,488,1495,638,1478" shape="poly">
			    <area href="javascript:void(0);" onclick="carga_archivo('contenedor_principal','cnb');" alt="CNB" title="CNB" coords="803,1417,882,1350,936,1279,980,1190,1002,1120,1013,1042,1013,962,1082,920,1142,876,1193,815,1226,763,1260,698,1285,619,1297,552,1437,663,1541,846,1563,1034,1528,1200,1451,1323,1321,1428,1168,1484,1009,1493,894,1467" shape="poly">
			    <area href="javascript:void(0);" alt="CNB-FGJ" title="CNB-FGJ" coords="781,1390,876,1302,932,1208,969,1106,980,1028,977,980,866,1012,776,1019,689,1008,627,992,587,980,594,1106,639,1217,686,1301" shape="poly">
			    <area href="javascript:void(0);" alt="CBP-CNB" title="CBP-CNB" coords="1013,920,1095,870,1164,794,1214,717,1253,630,1264,558,1145,522,1056,516,963,529,890,551,818,589,886,657,945,735,988,830" shape="poly">
			    <area href="javascript:void(0);" alt="CBP-FGJ" title="CBP-FGJ" coords="559,926,573,851,599,782,625,729,664,681,700,641,750,597,684,561,598,533,501,520,418,526,357,541,306,563,322,652,351,724,400,796,470,865" shape="poly">
			    <area href="javascript:void(0);" onclick="carga_archivo('contenedor_principal','unificada');" alt="CBP-CNB-FGJ" title="CBP-CNB-FGJ" coords="588,943,666,968,742,984,830,981,902,969,974,940,954,842,911,760,871,702,817,644,786,615,728,655,681,724,634,801" shape="poly">
		</map>
	</div>

</div>

<script>
    $(function () {
        ImageMap('img[usemap]');
    });
    function selectRegion(region) {
        document.querySelector("img").setAttribute('src', 'image-map-' + region + '.png');
    }

</script>
